SRC = si_main.cpp si_ppm.cpp si_image.cpp
OBJ = si_main.obj si_ppm.obj si_image.obj
CFLAGS = /c /EHsc /Zc:wchar_t /fp:precise /D_WIN32_WINNT=0x0500 /D "_MBCS" /D "_CONSOLE" /MD
LDFLAGS = /SUBSYSTEM:CONSOLE

all:
	cl $(CFLAGS) $(SRC)
	link /OUT:scaleit.exe $(LDFLAGS) $(OBJ)

clean:
	del *.obj *.exe *.res
