ASMDIR = C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
REFFLAGS = /r:"$(ASMDIR)\System.Xaml.dll" /r:"$(ASMDIR)\WindowsBase.dll" /r:"$(ASMDIR)\PresentationCore.dll" /r:"$(ASMDIR)\PresentationFramework.dll"

all:
	csc.exe /nologo /out:SetFontSizeProperty.exe /target:winexe $(REFFLAGS) SetFontSizeProperty.cs
	csc.exe /nologo /out:SetSpaceProperty.exe /target:winexe $(REFFLAGS) SetSpaceProperty.cs SpaceButton.cs SpaceWindow.cs
