REFFLAGS = /r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xaml.dll" /r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\WindowsBase.dll" /r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\PresentationCore.dll" /r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\PresentationFramework.dll"

all:
	csc.exe /nologo /out:SayHello.exe /target:winexe $(REFFLAGS) SayHello.cs
	csc.exe /nologo /out:HandleAnEvent.exe /target:winexe $(REFFLAGS) HandleAnEvent.cs
	csc.exe /nologo /out:InheritTheApp.exe /target:winexe $(REFFLAGS) InheritTheApp.cs
	csc.exe /nologo /out:ThrowWindowParty.exe /target:winexe $(REFFLAGS) ThrowWindowParty.cs
	csc.exe /nologo /out:GrowAndShrink.exe /target:winexe $(REFFLAGS) GrowAndShrink.cs
	csc.exe /nologo /out:TypeYourTitle.exe /target:winexe $(REFFLAGS) TypeYourTitle.cs