ASMDIR = C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
REFFLAGS = /r:"$(ASMDIR)\System.Xaml.dll" /r:"$(ASMDIR)\WindowsBase.dll" /r:"$(ASMDIR)\PresentationCore.dll" /r:"$(ASMDIR)\PresentationFramework.dll"

all:
	csc.exe /nologo /out:ListColorNames.exe /target:winexe $(REFFLAGS) ListColorNames.cs
	csc.exe /nologo /out:ListColorValues.exe /target:winexe $(REFFLAGS) ListColorValues.cs
